### PR TITLE
added teleop control for PTU

### PR DESCRIPTION
**Pull request by kunzel**

### CODE REVIEW

**Comment by marc-hanheide** [comment]
H, K, L, J, O are the keys? Does that make sense? Doesn't look intuitive to me... why this layout and nothing that is more like a _cursor block_

**Comment by kunzel** [comment]
Have you never used VI? ;) Then it is actually quite intuitive since these
are the keys to move around. The 'o' is just for origin. But I am also
happy if you change it.

**Comment by marc-hanheide** [comment]
Aaah, nope, I didin't know that. I try to stay away from vi I have to admit, but I'm sure I can adapt if need be. So, feel free to leave as is. Also, I take this as another piece of evidence that vi **is** unintuitive.

**Comment by kunzel** [comment]
After some time of using these keys will become very intuitive, trust me. They are also easy to find because of the little bumper on the 'j' key. However, the main problem with the arrow keys is that they interfere with the scrolling behaviour of the browser.

**Comment by kunzel** [comment]
Realizes #15

**Pull request merged**
