### PR TITLE
Refactoring of repository structure

### LINKED ISSUE #31: Refactor repository structure
Make use of original repositories roslibjs, ros2djs, ros3djs, etc

### PR DESCRIPTION
**Pull request by kunzel**
Included ROSLIBJS, ROS2DJS etc as submodules. Closes #31

### CODE REVIEW

**Comment by marc-hanheide** [comment]
@kunzel, do you want me to check this tomorrow on the real robot here?

**Comment by kunzel** [comment]
@marc-hanheide, would be nice of course. Tough tomorrow I'll will make further changes. So maybe you can also wait and test everything at once!? I will put the adapted nav2d widget into a forked repository of the original tool in order to make a pull request and bring the navigation _with_ orientation upstream.

**Comment by marc-hanheide** [comment]
Right-do, I'll wait then (or test nonetheless while we are tidying up the
mess on our Linda)

**Comment by kunzel** [comment]
@marc-hanheide, I've added my latest changes wrt to nav2js to the pull request. If you have some time, please have a look and try it out. If it is working for you I'll make a pull request to the official nav2djs repository. Thanks!

**Comment by marc-hanheide** [comment]
yep, will do tomorrow...

On 2 July 2013 17:20, Lars Kunze notifications@github.com wrote:

> @marc-hanheide https://github.com/marc-hanheide, I've added my latest
> changes wrt to nav2js to the pull request. If you have some time, please
> have a look and try it out. If it is working for you I'll make a pull
> request to the official nav2djs repository. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/strands-project/strands_webtools/pull/32#issuecomment-20356923
> .

## 

---

Dr. Marc Hanheide
Senior Lecturer in Computer Science
University of Lincoln
Brayford Pool
Lincoln, LN6 7TS
Phone: +44 1522 88 6966
EMail: marc@hanheide.net
Web: http://www.hanheide.net
skype: mah99de

**Comment by marc-hanheide** [comment]
sorry, I entirely forgot about this one today. And I won't be in tomorrow to test it. But if it works for you I'm sure it's safe to be merged now. Or we ask @cdondrup or @gestom to quickly test it on our robot first. Your call...

**Comment by hawesie** [comment]
It looks ok to me. We can always fix remaining errors after the merge.

**Pull request merged**
