### PR TITLE
Marathon: massive pull request with all the developments for the marathon

### PR DESCRIPTION
**Pull request by marc-hanheide**
I'd like to get this all back on the master branch, if people agree... of course, it'll mean a lot of changes being pulled in. This is to start the discussion if we want this or if we want it to remain in its separate branch. As most of the web stuff for the marathon is in a subdir `apache` the impact should be too severe. the top-level is pretty much unaffected. Please check and send your comments on this.

### CODE REVIEW

**Comment by hawesie** [comment]
As you're really the only person actively developing here, I can't see why we'd argue with this!

**Comment by marc-hanheide** [comment]
Ok, that's exactly what I wasn't sure about. Thanks

**Comment by kunzel** [comment]
Yes i agree with Nick. I'll test it for us tomorrow morning.

**Comment by kunzel** [comment]
@marc-hanheide , I've cloned the rosbridge_suite and the mjpg_server from the strands-project. After a catkin_make and sourcing the setup.bash, I still end up in the default ros installation packages. Any idea why this could happen? I have the strands_webtools in the same catkin_ws, and there a roscd works, ie. it overlays the /opt/strands workspace.

**Comment by kunzel** [comment]
@marc-hanheide , do you have a script that copies all relevant files (html, css, js) from strands_webtools to /opt/strands/lib/www?

**Comment by marc-hanheide** [comment]
@kunzel we had a similar issue with catkin workspaces a number of times. I cleaned the whole catkin WS by deleting `build` and `devel` and then catkin_make from scratch.

**Comment by marc-hanheide** [comment]
@kunzel in `apache` is a script `./install.sh` that copies everything correctly. I didn't finish the documentation yesterday. It was meant to be mentioned there. Please add missing bits as you go along.

**Comment by marc-hanheide** [comment]
also, I'm working on a mechanism to create the correct `marathon.html` from a `marathon.html.in` via cmake. I.e. one sets site-specific things in cmake (using `catkin_make -D ...`) and then it generates the correct marathon.html from that to then be installed via `install.sh`

**Comment by kunzel** [comment]
@marc-hanheide , I tried it already several times to delete devel/ and build/, but without any success. But now, that you have said it, it worked! WTF!

I will check out the install script. I already saw the make file for building the html page. If you are currently working on it, please make the title also configurable. 

thanks

**Comment by kunzel** [comment]
@marc-hanheide I also had to install the tf2_web_republisher package. Now, everything seems to to be working fine. Except that I don't get any ROS information displayed on the web page. I aasume that this is a firewall problem. Was there a way to test this from commandline or via a a service call?  How can I get the info from the websocket server?

**Comment by kunzel** [comment]
Hey @marc-hanheide , do you have an idea what might be the problem here?

console output:
[13:38:18.620] GET http://localhost/bob/rosws [HTTP/1.1 500 Internal Server Error 0ms]
[13:38:18.705] GET http://localhost/bob/video/stream?topic=/image_blurrer/output_video?width=560?height=420 [HTTP/1.1 500 Internal Server Error 0ms]
[13:38:18.626] Firefox can't establish a connection to the server at ws://localhost/bob/rosws. @ http://localhost/bob/roslibjs/build/roslib.js:431
[13:38:18.626] Error: Uncaught, unspecified 'error' event. @ http://localhost/bob/roslibjs/include/EventEmitter2/eventemitter2.js:285

**Comment by marc-hanheide** [comment]
Best is probably too have a hangout on this. Can't do it now in afraid. Either tonight or tomorrow afternoon.

**Comment by kunzel** [comment]
OK, thanks. I'll try to contact you then.

**Pull request merged**
